use catch_all to get terms instead of a plain args array

diff --git a/kbg b/kbg
--- a/kbg
+++ b/kbg
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.9 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -30,7 +30,7 @@ root_command() {
 
   fzf_cmd="fzf --multi"
 
-  eval "terms=(${args[term]})"
+  terms=("${other_args[@]}")
 
   if [ "${args[--any]:-}" != "" ]; then
       # find files with ANY term. easy case, `rg` supports this natively.
@@ -117,7 +117,7 @@ kbg_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  kbg TERM... [OPTIONS]\n"
+  printf "  kbg [OPTIONS] [--] TERMS...\n"
   printf "  kbg --help | -h\n"
   printf "  kbg --version | -v\n"
   echo
@@ -163,9 +163,8 @@ kbg_usage() {
     # :command.usage_args
     printf "%s\n" "Arguments:"
 
-    # :argument.usage
-    printf "  %s\n" "TERM..."
-    printf "    Term to search for\n"
+    echo "  TERMS..."
+    printf "    Terms to search for\n"
     echo
 
     # :command.usage_examples
@@ -178,12 +177,16 @@ kbg_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -194,6 +197,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -369,22 +375,21 @@ parse_requirements() {
         shift
         ;;
 
+      --)
+        shift
+        other_args+=("$@")
+        break
+        ;;
+
       -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
+        other_args+=("$1")
+        shift
         ;;
 
       *)
         # :command.parse_requirements_case
-        # :command.parse_requirements_case_repeatable
-        # :argument.case_repeatable
-        escaped="$(printf '%q' "$1")"
-        if [[ -z ${args['term']+x} ]]; then
-          args['term']="$escaped"
-        else
-          args['term']="${args['term']} $escaped"
-
-        fi
+        # :command.parse_requirements_case_catch_all
+        other_args+=("$1")
         shift
 
         ;;
@@ -392,9 +397,9 @@ parse_requirements() {
     esac
   done
 
-  # :command.required_args_filter
-  if [[ -z ${args['term']+x} ]]; then
-    printf "missing required argument: TERM\nusage: kbg TERM... [OPTIONS]\n" >&2
+  # :command.catch_all_filter
+  if [[ ${#other_args[@]} -eq 0 ]]; then
+    printf "missing required argument: TERMS...\nusage: kbg [OPTIONS] [--] TERMS...\n" >&2
     exit 1
   fi
 
